I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game/day_one.rpy", line 41, in script
    jump city_street_first
ScriptError: could not find label 'city_street_first'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game/day_one.rpy", line 41, in script
    jump city_street_first
  File "/home/dmitrii/renpy-8.2.1-sdk/renpy/ast.py", line 1698, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/dmitrii/renpy-8.2.1-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'city_street_first'.

Linux-5.15.0-71-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.2.1.24030407
Однажды в деревне! 1.0
Wed Aug 14 16:30:42 2024
